# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 650bd14f26a812fe6f79868ccf621d6d9aaf24442982dbead68b20e612c11c5e75b23ff80334e32c35e59a6edeaea577c36105e470b1eb77af1dd1fbeb845aab

test:
  secret_key_base: c16eb9a0f6c2f32b97b642f57e2e7665d4055c8d7abea126cd4d1ffa1dcc4ffd98cd20d70ecfb74b6d2a06dde2392a521ac2f12837df3bbf4758b761ca0334d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
